[versions]
minecraft = "1.19.2"
fabric_loader = "0.14.9"

fabric_api = "0.60.0+1.19.2"
mixin_extras = "0.0.12"
mod_menu = "4.0.6"
devauth = "1.1.0"
yacl = "1.5.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
mod_menu = { module = "com.terraformersmc:modmenu", version.ref = "mod_menu" }
mixin_extras = { module = "com.github.llamalad7:mixinextras", version.ref = "mixin_extras" }
devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
yacl = { module = "dev.isxander:yet-another-config-lib", version.ref = "yacl" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
